### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Noskillx** [niltwill/vc-updatedscm#2]
Hey, i just want to let you know that you havent added the new LOD model collission file for construction site which cause a crash after demolition man is passed and driving away... i'v done the fix for this as well as i updated readme with the information you'l need it otherwise game crash add this to gta3.img link:
https://drive.google.com/file/d/1I5JPhmWsjYcw8_gj5eYeYkx1P3H7S5iM/view
and a link to updated readme for the repo to let people know its important:
https://drive.google.com/file/d/1v7GGDYg-67pn9QInoXPkdtGY1Cd0rS-y/view?usp=sharing.
Thanks

**Comment by niltwill** [comment]
Thanks, I forgot about that one. Also does the yacht's gangplank remains attached after/while the "All Hands On Deck" mission still? I'm trying to workaround that now, but if the game is too stubborn, it's better to remove that prop in the first place (maybe that's the reason why it was cut from the game).
