### ISSUE TITLE
Niltwill you broke it.

### ISSUE THREAD

**Issue by Noskillx** [niltwill/vc-updatedscm#9]
What have you done? i am playing this again and it looks like my fixes are gone! like ability to loose the cops both on foot/in car in Trecherous Swine, Removed marker when cutscene in front of the hotel triggers and so on. (2.1e) EDIT: Also the weapon you had selected before anwsering phone call doesn't go back into your current weapon after phone call is over like i did it. I wanted to make more commits in a future but seeing how this is getting fucked up fixes actually being removed, i don't think i can re-do stuff each time you update something (or break)

**Comment by niltwill** [comment]
Sorry about that, it's just that I'm a bit of a mental person who cannot make himself organized and ends up breaking things where organization would be vital. I wasn't intentionally removing fixes, in fact I have no idea what went wrong or where, I'm simply confused and perplexed that something went wrong (I have no recollection of anything). Maybe you should take charge of this? I really am not up to this one it seems, my inability keeps interfering too much and makes a mess of things.

**Comment by Noskillx** [comment]
I DID want to but its messed up at the moment, don't know if i'l do anything. I'v had a huge plan to totally re-organize this mod like make a proper changelog etc, also looks like briefcase is also gone...
BTW if you want to hand me over the mod, can you pop in on the forum to at least give me the topic? or make a post that you allow me to take it so moderation can hand it over, it seems pretty dead right now however do note you will ALWAYS be marked as a main creator of this in the topic/everywhere else.

**Comment by niltwill** [comment]
Well the changes [can be reviewed and restored with the commits](https://github.com/niltwill/vc-updatedscm/commits/master), right? And how to give the topic ownership to you?

**Comment by Noskillx** [comment]
Sure thing we can still cooperate just please organize your stuff from now on 😊

**Comment by Noskillx** [comment]
Is there a better place to contact you? can you please join discord or something? we'r all there Noskillx #4751 find me on discord.

**Comment by niltwill** [comment]
Yep, first, I have to try fixing what went wrong, and be a lot more careful from now on. And luckily since there's nothing else to do now, I can already begin to do the file merges even here, a Linux OS makes it easier for me at work.

+ OK, I'll try Discord.

**Comment by Noskillx** [comment]
Great, Discord is where the whole modding community is now, including me Silent,Tomasak and pretty much all others.

**Comment by niltwill** [comment]
OK, the issue was that I uploaded older scm files from a different folder, not used the proper source.
